FROM debian AS base
WORKDIR /app
RUN apt update
RUN apt install -y libwebkit2gtk-4.1-dev \
      build-essential
COPY . .
RUN cargo tauri build
RUN apt-get update && apt-get install -y \
    libssl-dev \
    pkg-config \
    ca-certificates 
ENTRYPOINT ["/usr/local/bin/folio-worker"]
