name: CI/CD
env:
  CARGO_TERM_COLOR: always
  JUST_VERSION: '1.46.0'
on:
  pull_request:
    branches: ["main","v**","qt"]
  push:
    branches: ["main","qt"]
concurrency:
  group: ci-${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
#        with:
#          version: 6.11.1
      - run: xmake build -y folio
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v3
        with:
          just-version: ${{env.JUST_VERSION}}
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Install system dependencies
        if: ${{runner.os == 'Linux'}}
        run: sudo apt update
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
#        with:
#          version: 6.11.1
      - name: Run tests
        run: xmake run -y test
#      - name: Install system dependencies
#        if: ${{runner.os == 'Linux'}}
#        run: |
#          sudo apt update
#          sudo apt install libwebkit2gtk-4.1-dev \
#            build-essential \
#            curl \
#            wget \
#            file \
#            libxdo-dev \
#            libssl-dev \
#            libayatana-appindicator3-dev \
#            librsvg2-dev
  pass:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Complete
        run: echo All good!
