name: Post release
env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite://data.db
on:
  pull_request: 
    branches: [main]
  release:
    types: [released]
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: post-release
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - name: Update release-info.json
        run: cargo run -p folio-updater
      - uses: EndBug/add-and-commit@v10
        with:
          default_author: github_actions
          message: "Update release-info.json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
