name: CI/CD
on:
  pull_request:
    branches: ["main"]
  push: 
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: rust-cache-${{runner.os}}-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            rust-cache-${{runner.os}}-
            rust-cache-
          path: |
            target/
            ~/.cargo
      - run: cargo clippy --all-features --all-targets -- -D warnings
